protect:
  admins:
  - 'Gold_edenarogka' #Никнеймы администраторов
  ip:
  - /127.0.0.1 #Адреса, с которых могут заходить администраторы
  kick-message: "Нельзя заходить под этим никнеймом" #Сообщение о неудачной проверке